//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generatorRestauracji
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuisine
    {
        public Cuisine()
        {
            this.RestaurantCuisines = new HashSet<RestaurantCuisine>();
        }
    
        public int CuisineId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<RestaurantCuisine> RestaurantCuisines { get; set; }
    }
}
