//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generatorRestauracji
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryAddress
    {
        public int DeliveryAddressId { get; set; }
        public System.Guid UserId { get; set; }
        public int AddressId { get; set; }
        public string FlatNumber { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual User User { get; set; }
    }
}
