//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generatorRestauracji
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishGroup
    {
        public DishGroup()
        {
            this.Dishes = new HashSet<Dish>();
        }
    
        public int DishGroupId { get; set; }
        public string Name { get; set; }
        public System.Guid RestaurantId { get; set; }
    
        public virtual ICollection<Dish> Dishes { get; set; }
    }
}
