//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generatorRestauracji
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        public int DishId { get; set; }
        public System.Guid RestaurantId { get; set; }
        public string DishName { get; set; }
        public int DishGroupId { get; set; }
        public decimal Price { get; set; }
        public int ImageId { get; set; }
    
        public virtual DishGroup DishGroup { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
