//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generatorRestauracji
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpeningHour
    {
        public int OpeningId { get; set; }
        public System.Guid RestaurantId { get; set; }
        public short Day { get; set; }
        public System.TimeSpan TimeFrom { get; set; }
        public System.TimeSpan TimeTo { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
