//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generatorRestauracji
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderState
    {
        public OrderState()
        {
            this.Orders = new HashSet<Order>();
            this.OrderStatesHistories = new HashSet<OrderStatesHistory>();
        }
    
        public int OrderStateId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<OrderStatesHistory> OrderStatesHistories { get; set; }
    }
}
