//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generatorRestauracji
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDishes = new HashSet<OrderDish>();
            this.OrderStatesHistories = new HashSet<OrderStatesHistory>();
            this.Payments = new HashSet<Payment>();
        }
    
        public System.Guid OrderId { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int DeliveryTypeId { get; set; }
        public string DeliveryData { get; set; }
        public System.Guid RestaurantId { get; set; }
        public int OrderStateId { get; set; }
    
        public virtual DeliveryType DeliveryType { get; set; }
        public virtual ICollection<OrderDish> OrderDishes { get; set; }
        public virtual OrderState OrderState { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<OrderStatesHistory> OrderStatesHistories { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
