//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generatorRestauracji
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public Payment()
        {
            this.PaymentsHistories = new HashSet<PaymentsHistory>();
        }
    
        public System.Guid PaymentId { get; set; }
        public int PaymentTypeId { get; set; }
        public decimal Amount { get; set; }
        public int PaymentStateId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.Guid OrderId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual PaymentState PaymentState { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual ICollection<PaymentsHistory> PaymentsHistories { get; set; }
    }
}
