//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generatorRestauracji
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentsHistory
    {
        public int PaymentHistoryId { get; set; }
        public System.Guid PaymentId { get; set; }
        public int PaymentStateId { get; set; }
        public System.DateTime ModificationDate { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual PaymentState PaymentState { get; set; }
    }
}
