//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace generatorRestauracji
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantCuisine
    {
        public System.Guid RestaurantId { get; set; }
        public int CuisineId { get; set; }
        public int RestaurantCuisineId { get; set; }
    
        public virtual Cuisine Cuisine { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
